#!/bin/sh

# This script will launch apps in web app windows using flatpak chrome

# Make sure you have create a /srv/app directory with privs to your user
# sudo mkdir -p /srv/app/chrome; sudo chown $USER:$USER /srv/app/chrome

usage() { echo "Usage: $0 [-cryptogv]" 1>&2; exit 1; }

while getopts ":cryptogv" o; do
    case "${o}" in
        p)
            flatpak run com.google.Chrome --app=http://10.2.2.20:32400/web/index.html --user-data-dir=/srv/app/chrome --class="iPlex"
            ;;
        y)
            flatpak run com.google.Chrome --app=https://youtube.com/ --user-data-dir=/srv/app/chrome --class="iYoutube"
            ;;
        g)
            flatpak run com.google.Chrome --app=https://play.geforcenow.com/ --user-data-dir=/srv/app/chrome --class="iGeforce"
            ;;
        c)
            flatpak run com.google.Chrome --user-data-dir=/srv/app/chrome --class="iChrome"
            ;;
        o)
            flatpak run com.google.Chrome --app=https://outlook.office.com/  --user-data-dir=/srv/app/chrome --class="iOutlook"
            ;;
        t)
            flatpak run com.google.Chrome --app=https://teams.microsoft.com/ --user-data-dir=/srv/app/chrome --class="iTeams"
            ;;
        r)
            flatpak run com.google.Chrome --app=https://rpg.sim.pub/ --user-data-dir=/srv/app/chrome --class="iRPG"
            ;;
        v)
            flatpak run com.google.Chrome -proxy-server="10.1.1.10:3127" --incognito --user-data-dir=$HOME/.app/brave_vpn
            ;;
        *)
            usage
            ;;
    esac
done
shift $((OPTIND-1))
