#!/bin/sh

# Get Default Mic ID
mic_id=`pacmd list-sources | grep -A 15 '* index' | awk '/index/{ print $3 }' | sed 's/#//g'`
mute_state=`pacmd list-sources | grep -A 15 '* index' | awk '/muted/{ print $2 }' | sed 's/#//g'`

pactl set-source-mute $mic_id 1
dunstify -h string:x-canonical-private-synchronous:mic " Microphone is Off " -t 4000 -I ~/.config/icons/mic_fluent_mute.png
