#!/bin/sh



. ~/.${1}

#wlfreerdp /u:${uname} /p:${upass} /v:${hname} +fonts /dynamic-resolution -grab-keyboard
#wlfreerdp /u:${uname} /p:${upass} /v:${hname} -grab-keyboard /h:1400  /w:2560 -grab-keyboard
xfreerdp /cert-ignore /u:${uname} /p:${upass} /v:${hname} -grab-keyboard /dynamic-resolution  -grab-keyboard

